-- Generated by spritter v1.8.2 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 2 },
  ["file_count"] = 1,
  ["height"] = 128,
  ["line_length"] = 4,
  ["lines_per_file"] = 4,
  ["scale"] = 0.5,
  ["shift"] = {-17 / 64, -42 / 64},
  ["sprite_count"] = 16,
  ["width"] = 134,
}
