return {
    type = "fluid",
    name = "fusioning-lava",
    subgroup = "fluid",
    default_temperature = 1500,
    max_temperature = 2000,
    heat_capacity = "1kJ",
    base_color = { r = 1.0, g = 0.4, b = 0.0 },
    flow_color = { r = 1.0, g = 0.6, b = 0.2 },
    icon = "__base__/graphics/icons/fluid/light-oil.png",
    icon_size = 64,
    order = "a[fluid]-e[fusioning-lava]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    auto_barrel = true,
}
