return {
    type = "fluid",
    name = "stronger-fusioning-lava",
    subgroup = "fluid",
    default_temperature = 2000,
    max_temperature = 3000,
    heat_capacity = "1.5kJ",
    base_color = { r = 1.0, g = 0.2, b = 0.0 },
    flow_color = { r = 1.0, g = 0.4, b = 0.1 },
    icon = "__base__/graphics/icons/fluid/heavy-oil.png",
    icon_size = 64,
    order = "a[fluid]-f[stronger-fusioning-lava]",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
    auto_barrel = true,
}
