data:extend({
    require("prototypes.fluids.liquid-nitrogen"),
    require("prototypes.fluids.gases.argon"),
    require("prototypes.fluids.gases.air"),
    require("prototypes.fluids.gases.compressed-air"),
    require("prototypes.fluids.gases.chlorine"),
    require("prototypes.fluids.fusioning-lava"),
    require("prototypes.fluids.stronger-fusioning-lava"),
    require("prototypes.fluids.enchanted-lava"),
})