require("prototypes.items.foundation-platform")
require("prototypes.items.trains.fluid-wagon")
require("prototypes.items.trains.cargo-wagon")
require("prototypes.items.trains.locomotive")
require("prototypes.items.storage-tank")
require("prototypes.items.slug")
require("prototypes.items.landfill")
